[project]
name = "opencode-power-pack"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Rafid K.", email = "rafidka@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
opencode-power-pack = "opencode_power_pack:main"
op2 = "opencode_power_pack:main"

[build-system]
requires = ["uv_build>=0.11.12,<0.12.0"]
build-backend = "uv_build"
